name: test
on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build-macos:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        target: [ arm64 ]
        
    steps:
      - name: ✅ -march=native
        run: clang -mcpu=apple-a15 -dM -E - </dev/null

      - name: ✅ -arch arm64
        run: clang -arch arm64 -dM -E - </dev/null

      - name: ❌ -mcpu=apple-a15 --target=arm64-apple-ios17.0
        if: ${{ success() || failure() }}
        run: clang -isysroot $(xcrun --sdk iphoneos --show-sdk-path) -mcpu=apple-a15 --target=arm64-apple-ios17.0 -dM -E - </dev/null

      - name: ❌ -mcpu=apple-a15 -arch arm64
        if: ${{ success() || failure() }}
        run: clang -mcpu=apple-a15 -arch arm64 -dM -E - </dev/null
        
      - uses: actions/checkout@v4
      - name: install requirements
        run: pip3 install -r requirements.txt
      - name: Package
        env:
            GITHUB_USERNAME: ${{ github.actor }}
            GITHUB_TOKEN: ${{ secrets.LLVM_ENV }}
        run: ./package_llvm.py --target-architecture arm64-apple-ios17.0

      - name: Package
        env:
            GITHUB_USERNAME: ${{ github.actor }}
            GITHUB_TOKEN: ${{ secrets.LLVM_ENV }}
        run: ./upload_clang.py --target-architecture arm64-apple-ios17.0
